<?php

/**
 * @file
 * Contains qrcode_fields.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function qrcode_fields_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  if ($route_name === 'help.page.qrcode_fields') {
    $output = nl2br(file_get_contents(__DIR__ . '/README.txt'));
  }
  return $output;
}

/**
 * Implements hook_multiple_field_remove_button_field_types_alter().
 */
function qrcode_fields_multiple_field_remove_button_field_types_alter(array &$fieldTypes) {
  // Drupal multiple value field have no option to remove item.
  // @see https://www.drupal.org/project/drupal/issues/1038316
  // This optional hook adds ability to remove added items.
  // Requires "multiple_field_remove_button" module to be enabled.
  // @see https://www.drupal.org/project/multiple_fields_remove_button
  $fieldTypes[] = 'qrcode_fields';
}

/**
 * Formats a DateTime object into the iCalendar format.
 *
 * This function takes a datetime string and a timezone, creates
 * a DateTime object, and formats it into the iCalendar format
 * (e.g., 20230101T123000Z).
 *
 * @param string $dateTime
 *   The datetime string to format.
 * @param string $timezone
 *   The timezone in which the datetime should be interpreted.
 *
 * @return string
 *   The formatted datetime string in the iCalendar format.
 */
function qrcode_fields_format_ical_date_time($dateTime, $timezone) {
  $dateTime = new DateTime($dateTime, new DateTimeZone($timezone));
  return $dateTime->format('Ymd\THis\T');
}
